from __future__ import annotations

import numpy as np

class IndexFlatIP:
    def __init__(self, d: int) -> None: ...
    def add(self, x: np.ndarray) -> None: ...
    def search(self, x: np.ndarray, k: int) -> tuple[np.ndarray, np.ndarray]: ...

def normalize_L2(x: np.ndarray) -> None: ...
